from setuptools import setup
import os

# Read the README file for long description
def read_readme():
    here = os.path.abspath(os.path.dirname(__file__))
    readme_path = os.path.join(here, 'README.md')
    if os.path.exists(readme_path):
        with open(readme_path, 'r', encoding='utf-8') as f:
            return f.read()
    return ''

packages = \
['omnizart',
 'omnizart.beat',
 'omnizart.chord',
 'omnizart.cli',
 'omnizart.cli.beat',
 'omnizart.cli.chord',
 'omnizart.cli.drum',
 'omnizart.cli.music',
 'omnizart.cli.patch_cnn',
 'omnizart.cli.vocal',
 'omnizart.cli.vocal_contour',
 'omnizart.constants',
 'omnizart.constants.schema',
 'omnizart.drum',
 'omnizart.feature',
 'omnizart.models',
 'omnizart.music',
 'omnizart.patch_cnn',
 'omnizart.vocal',
 'omnizart.vocal_contour']

package_data = \
{'': ['*'],
 'omnizart': ['checkpoints/beat/beat_blstm/*',
              'checkpoints/beat/beat_blstm/variables/variables.index',
              'checkpoints/chord/chord_v1/configurations.yaml',
              'checkpoints/chord/chord_v1/configurations.yaml',
              'checkpoints/chord/chord_v1/saved_model.pb',
              'checkpoints/chord/chord_v1/saved_model.pb',
              'checkpoints/chord/chord_v1/variables/variables.index',
              'checkpoints/drum/drum_keras/*',
              'checkpoints/drum/drum_keras/variables/variables.index',
              'checkpoints/music/music_note_stream/*',
              'checkpoints/music/music_note_stream/variables/variables.index',
              'checkpoints/music/music_piano-v2/*',
              'checkpoints/music/music_piano-v2/variables/variables.index',
              'checkpoints/music/music_piano/*',
              'checkpoints/music/music_piano/variables/variables.index',
              'checkpoints/music/music_pop/*',
              'checkpoints/music/music_pop/variables/variables.index',
              'checkpoints/patch_cnn/patch_cnn_melody/*',
              'checkpoints/patch_cnn/patch_cnn_melody/variables/variables.index',
              'checkpoints/vocal/vocal_contour/*',
              'checkpoints/vocal/vocal_contour/variables/variables.index',
              'checkpoints/vocal/vocal_semi/*',
              'checkpoints/vocal/vocal_semi/variables/variables.index',
              'defaults/*',
              'resource/vamp/*']}

install_requires = \
['click>=8.0.0',
 'jsonschema>=4.0.0',
 'librosa>=0.10.0',
 'madmom>=0.16.1',
 'mir_eval>=0.7',
 'pillow>=10.0.0',
 'pretty_midi>=0.2.9',
 'pyfluidsynth>=1.3.0',
 'pyyaml>=6.0',
 'demucs>=4.0.0',
 'tensorflow>=2.13.0',
 'torch>=2.0.0',
 'torchaudio>=2.0.0',
 'tqdm>=4.65.0',
 'urllib3>=1.26.0',
 'vamp>=1.1.0',
 'numpy>=1.21.0',
 'scipy>=1.7.0',
 'h5py>=3.0.0']

entry_points = \
{'console_scripts': ['omnizart = omnizart.cli.cli:entry']}

setup_kwargs = {
    'name': 'omnizart',
    'version': '0.5.0',
    'description': 'Omniscient Mozart, being able to transcribe everything in the music.',
    'long_description': read_readme(),
    'long_description_content_type': 'text/markdown',
    'author': 'BreezeWhite',
    'author_email': 'miyashita2010@tuta.io',
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://sites.google.com/view/mctl/home',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.8,<3.11',
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
